In [1]:
import pickle
from agents.nnAgent import nnModel, train_test_splitter
import tensorflow as tf

In [33]:
tf.compat.v1.reset_default_graph()

policy_model = nnModel('policy')
policy_model.build_model(3)

v_model = nnModel('state_value')
v_model.build_model(3)

In [3]:
nb_passes = 3
nb_files = 22
nb_epochs = 5
batch_size = 1024

In [ ]:
for it in range(nb_passes):
    print(f'Pass #{it}')
    for i in range(nb_files):
        path = f'./data/it_{i}_v2.pkl'
        with open(path, 'rb') as f:
            data = pickle.load(f)
        print(f'learning using "{path}"')
        X = data['state']
        y = data['y']
        v = data['v']
        X_train, X_test, y_train, y_test = train_test_splitter(X, y, 0.05)
        
        policy_model.fit(X_train,
                         y_train,
                         X_test,
                         y_test,
                         epoch=nb_epochs,
                         batch_size=batch_size)
        
policy_model.save('rule_based_policy')

In [1]:
for it in range(nb_passes):
    print(f'Pass #{it}')
    for i in range(nb_files):
        path = f'./data/it_{i}_v2.pkl'
        with open(path, 'rb') as f:
            data = pickle.load(f)
        print(f'learning using "{path}"')
        X = data['state']
        y = data['y']
        v = data['v']
        X_train, X_test, y_train, y_test, v_train, v_test = train_test_splitter(X, y, 0.05, v=v)

        v_model.fit(X_train,
                    v_train,
                    X_test,
                    v_test,
                    epoch=nb_epochs,
                    batch_size=batch_size)
v_model.save('state_value')

NameError: name 'nb_passes' is not defined

In [19]:
data['state']

[array([[-0.4375],
        [-0.4375],
        [-0.4375],
        ...,
        [-0.1875],
        [-0.125 ],
        [-0.125 ]]),
 array([[-0.4375],
        [-0.4375],
        [-0.375 ],
        ...,
        [ 0.125 ],
        [ 0.125 ],
        [ 0.125 ]]),
 array([[-1.  ],
        [-0.95],
        [-0.9 ],
        ...,
        [ 0.3 ],
        [ 0.35],
        [ 0.4 ]]),
 array([[-1.  ],
        [-0.99],
        [-0.98],
        ...,
        [-0.34],
        [-0.33],
        [-0.32]]),
 array([[ 0. ],
        [ 0. ],
        [-0.1],
        ...,
        [-0.5],
        [-0.4],
        [-0.4]]),
 array([[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]]),
 array([[0],
        [0],
        [5],
        ...,
        [0],
        [0],
        [0]]),
 array([[15],
        [ 3],
        [ 0],
        ...,
        [ 0],
        [ 0],
        [ 0]]),
 array([[ 0],
        [ 0],
        [ 0],
        ...,
        [ 0],
        [ 0],
        [15]]),
 array([[ 0],

In [17]:
data['v']

[6.666666664089872,
 6.666666663635144,
 6.6666666631001705,
 6.6666666624707895,
 6.666666661730341,
 6.666666660859225,
 6.666666659834383,
 6.666666658628686,
 6.666666657210219,
 6.666666655541434,
 6.666666653578157,
 6.66666665126842,
 6.666666648551082,
 6.666666645354215,
 6.666666641593194,
 6.666666637168464,
 6.666666631962899,
 6.666666625838705,
 6.66666661863377,
 6.666666610157377,
 6.66666660018515,
 6.6666665884531175,
 6.666666574650727,
 6.66666655841262,
 6.666666539308966,
 6.666666516834077,
 6.666666490393032,
 6.666666459285921,
 6.666666422689318,
 6.666666379634493,
 6.666666328981757,
 6.666666269390302,
 6.666666199282709,
 6.666666116803187,
 6.6666660197684555,
 6.666665905609948,
 6.666665771305821,
 6.666665613300966,
 6.666665427412901,
 6.66666520872106,
 6.666664951436542,
 6.666664648748873,
 6.666664292645733,
 6.666663873700863,
 6.666663380824545,
 6.6666628009700535,
 6.666662118788298,
 6.666661316221528,
 6.666660372025326,
 6.6666592612062665,

In [ ]:
def add_advantage(X, model):
    

In [1]:
import pickle
from agents.nnAgent import nnModel, train_test_splitter
import tensorflow as tf

In [2]:
reinforce_model = nnModel('actor_critic')

In [3]:
path = f'./data/it_0_v2.pkl'

In [4]:
with open(path, 'rb') as f:
    data = pickle.load(f)

In [5]:
X = data['state']
y = data['y']
v = data['v']
X_train, X_test, y_train, y_test, v_train, v_test = train_test_splitter(X, y, 0.05, v=v)

In [6]:
reinforce_model.build_model()

In [7]:
X_test2 = X_test + [v_test]

In [8]:
X_train2 = X_train + [v_train]

In [22]:
policy_model.build_model()

In [11]:
reinforce_model.predict(X_test)

array([[0.2707125 , 0.2513453 , 0.22590981, 0.2520324 ],
       [0.19331466, 0.22725874, 0.31421083, 0.26521572],
       [0.24475338, 0.2635193 , 0.25421354, 0.23751374],
       [0.2590985 , 0.24802794, 0.23698923, 0.25588438],
       [0.20159769, 0.23186167, 0.30598143, 0.2605593 ],
       [0.23178771, 0.2537843 , 0.2683345 , 0.24609353],
       [0.24947914, 0.24418765, 0.26008546, 0.24624771],
       [0.22400893, 0.24987115, 0.27230942, 0.25381052],
       [0.24556835, 0.2650649 , 0.25942785, 0.22993891],
       [0.27468607, 0.27917215, 0.22837645, 0.21776542],
       [0.23816544, 0.23292162, 0.2681064 , 0.26080653],
       [0.26135236, 0.2509886 , 0.24235629, 0.24530281],
       [0.22897157, 0.23685037, 0.2702013 , 0.2639767 ],
       [0.2311213 , 0.26255873, 0.27154806, 0.234772  ],
       [0.27146247, 0.23608547, 0.22622305, 0.26622903],
       [0.24874417, 0.24831113, 0.25047916, 0.25246546],
       [0.2400413 , 0.23093966, 0.253831  , 0.27518812],
       [0.26768145, 0.23319142,

In [10]:
reinforce_model.predict(X_test2)

array([[0.2707125 , 0.2513453 , 0.22590981, 0.2520324 ],
       [0.19331466, 0.22725874, 0.31421083, 0.26521572],
       [0.24475338, 0.2635193 , 0.25421354, 0.23751374],
       [0.2590985 , 0.24802794, 0.23698923, 0.25588438],
       [0.20159769, 0.23186167, 0.30598143, 0.2605593 ],
       [0.23178771, 0.2537843 , 0.2683345 , 0.24609353],
       [0.24947914, 0.24418765, 0.26008546, 0.24624771],
       [0.22400893, 0.24987115, 0.27230942, 0.25381052],
       [0.24556835, 0.2650649 , 0.25942785, 0.22993891],
       [0.27468607, 0.27917215, 0.22837645, 0.21776542],
       [0.23816544, 0.23292162, 0.2681064 , 0.26080653],
       [0.26135236, 0.2509886 , 0.24235629, 0.24530281],
       [0.22897157, 0.23685037, 0.2702013 , 0.2639767 ],
       [0.2311213 , 0.26255873, 0.27154806, 0.234772  ],
       [0.27146247, 0.23608547, 0.22622305, 0.26622903],
       [0.24874417, 0.24831113, 0.25047916, 0.25246546],
       [0.2400413 , 0.23093966, 0.253831  , 0.27518812],
       [0.26768145, 0.23319142,

In [24]:
policy_model.predict(data['next_state'])

ValueError: When using data tensors as input to a model, you should specify the `steps` argument.

In [88]:
reinforce_model.predict(X_train2)

ValueError: Tensor Tensor("dense_5/Softmax:0", shape=(None, 4), dtype=float32) is not an element of this graph.

In [14]:
import numpy as np

In [15]:
np.zeros(shape=X_test[0].shape)

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [12]:
X_test[0].shape

(7302, 1)

In [10]:
len(X_test)

82

In [ ]:
1. Copy weights from rule_based model to reinforce model
2. set 2 versions of v_model
3. loop:
    Run simulations
    get training data
    add advantage estimate
    train reinforce model

In [34]:
v_model.load('state_value')

In [78]:
def compute_advantage(data, model):
    cur_state_val = v_model.predict(data['state'])
    next_state_val = np.array(data['reward']).reshape(-1, 1) + 0.85*v_model.predict(data['next_state'])*(np.array(data['done']) == False)
    return (next_state_val - cur_state_val).reshape(-1, 1)

In [70]:
cur_state_val

array([[ 6.670556],
       [ 6.670519],
       [ 6.67069 ],
       ...,
       [ 9.093634],
       [ 9.553383],
       [10.162241]], dtype=float32)

In [72]:
next_v = v_model.predict(data['next_state'])

In [74]:
r = np.array(data['reward'])

In [77]:
next_v

array([[ 6.670519 ],
       [ 6.67069  ],
       [ 6.6710367],
       ...,
       [ 9.553383 ],
       [10.162241 ],
       [10.162241 ]], dtype=float32)

In [71]:
next_state_val

array([[ 6.66994143,  6.66994143,  6.66994143, ...,  6.66994143,
         6.66994143, 10.        ],
       [ 6.67008686,  6.67008686,  6.67008686, ...,  6.67008686,
         6.67008686, 10.        ],
       [ 6.67038155,  6.67038155,  6.67038155, ...,  6.67038155,
         6.67038155, 10.        ],
       ...,
       [ 9.12037563,  9.12037563,  9.12037563, ...,  9.12037563,
         9.12037563, 10.        ],
       [ 9.63790512,  9.63790512,  9.63790512, ...,  9.63790512,
         9.63790512, 10.        ],
       [ 9.63790512,  9.63790512,  9.63790512, ...,  9.63790512,
         9.63790512, 10.        ]])

In [79]:
advantage = compute_advantage(data, v_model)

In [80]:
advantage

array([[-6.14643097e-04],
       [-6.14643097e-04],
       [-6.14643097e-04],
       ...,
       [ 8.47566414e+00],
       [ 8.47566414e+00],
       [-1.62240982e-01]])

In [82]:
np.mean(advantage>0)

0.1785657269978007

In [ ]:
def add_state_value(discount, steps):
    steps_back = steps[::-1]
    v_prime = 0
    for step in steps_back:
        v = step['reward'] + discount*v_prime
        v_prime = v
        step['v'] = v
    return None

In [54]:
1+0.85*6.666528624616389

6.666549330923931

In [50]:
1 + 0.8* (1+ 0.8* (1+ 0.8*(1)))

2.9520000000000004

In [87]:
np.zeros(10).tolist()

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [63]:
data['state'][0].shape

(1487, 1)

In [66]:
data['reward'][1485]

1

In [46]:
v_model.predict(data['state'])

array([[ 6.670556],
       [ 6.670519],
       [ 6.67069 ],
       ...,
       [ 9.093634],
       [ 9.553383],
       [10.162241]], dtype=float32)

In [67]:
1+0.85*10.162241 - 9.553383

0.08452184999999979

In [47]:
v_model.predict(data['next_state'])

array([[ 6.670519 ],
       [ 6.67069  ],
       [ 6.6710367],
       ...,
       [ 9.553383 ],
       [10.162241 ],
       [10.162241 ]], dtype=float32)

In [45]:
advantage

array([[-0.33414078],
       [-0.33414078],
       [-0.33414078],
       ...,
       [-1.03244781],
       [-1.03244781],
       [-0.16224098]])

In [37]:
data['reward']

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 -10,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 16.666655795888097,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 

In [36]:
v_model.predict(data['next_state'])

array([[ 6.670519 ],
       [ 6.67069  ],
       [ 6.6710367],
       ...,
       [ 9.553383 ],
       [10.162241 ],
       [10.162241 ]], dtype=float32)